servers: 
 - 
   url: /
 - 
   url: localhost
openapi: 3.0.0
info: 
 description: test api
 title: title
 version: 2.0.0
paths: 
 /testPost: 
  post: 
   requestBody: 
    content: 
     application/x-www-form-urlencoded: 
      schema: 
       type: object
       properties: 
        a: 
         type: string
         example: 12a3
        b: 
         format: float
         type: number
         example: 12.34
   description: request without urlParam
   responses: 
    200: 
     description: response with code 200
     content: 
      application/json: 
       schema: 
        type: object
        properties: 
         test: 
          type: integer
          example: 456
    502: 
     description: response with code 502
