servers: 
 - 
   url: /
 - 
   url: localhost
openapi: 3.0.0
info: 
 description: test api
 title: title
 version: 2.0.0
paths: 
 /service/update2/json: 
  post: 
   requestBody: 
    content: 
     application/json: 
      schema: 
       type: object
       properties: 
        request: 
         type: object
         properties: 
          acceptformat: 
           type: string
           example: crx2,crx3
          os: 
           type: object
           properties: 
            arch: 
             type: string
             example: x86_64
            version: 
             type: string
             example: 10.0.19043.1165
            platform: 
             type: string
             example: Windows
          "@updater": 
           type: string
           example: chrome
          sessionid: 
           type: string
           example: {256234d9-8523-46c0-b50a-6acd5da81d8a}
          dedup: 
           type: string
           example: cr
          hw: 
           type: object
           properties: 
            physmemory: 
             type: integer
          nacl_arch: 
           type: string
           example: x86-64
          updater: 
           type: object
           properties: 
            updatepolicy: 
             type: integer
            lastchecked: 
             type: integer
            name: 
             type: string
             example: Omaha
            laststarted: 
             type: integer
            version: 
             type: string
             example: 1.3.36.102
          updaterversion: 
           type: string
           example: 92.0.4515.159
          protocol: 
           type: string
           example: 3.1
          requestid: 
           type: string
           example: {66704bb4-22bc-44b2-ae74-d866bdbc7a54}
          prodversion: 
           type: string
           example: 92.0.4515.159
          arch: 
           type: string
           example: x64
          lang: 
           type: string
           example: zh-CN
          "@os": 
           type: string
           example: win
   description: request with urlParam
   responses: 
    200: 
     description: response with code 200
   parameters: 
    - 
      schema: 
       type: string
       example: 11:2678313091
      in: query
      name: cup2key
    - 
      schema: 
       type: string
       example: cebe54fa97bb5c5119a14c19d0f027a0229df4d79eef1632a9d2de0a30ea9b39
      in: query
      name: cup2hreq
 /generate_204: 
  get: 
   description: request without urlParam
   responses: 
    204: 
     description: response with code 204
 /pc/module/transhelper/upswitch.dat: 
  get: 
   description: request without urlParam
   responses: 
    200: 
     description: response with code 200
